### ISSUE TITLE
No communications happen between an Android phone and iOS phone running the app

### ISSUE THREAD

**Issue by shekoufa** [opentrace-community/opentrace-android#11]
I have managed to build the application on both Android and iOS. The app is running on two iPhones and two Android phones. The two iPhones communicate with each other through Bluetooth and so do the Android phones, however, I haven't been able to see any records for communication between any of the iPhones with any of the Android phones. Am I missing anything here? Is there any specific configuration that needs to be the same on both builds? Is that communication not possible by design, at all? U can provide further information about the two builds upon request.

**Comment by rinekri** [comment]
It happens because android and ios samples have different UUID and CHARACTERISTICS constants. You can fix it with 2 approaches: 1) copy and paste both from one sample to another, for example from android to ios or from ios to android; 2) [generate](https://github.com/opentrace-community/opentrace-android/issues/10#issuecomment-613130247) them and use on both platforms same values. I didn't check the second, but [theoretically](https://www.oreilly.com/library/view/getting-started-with/9781491900550/ch04.html) it should work.

**Comment by shekoufa** [comment]
Thanks @rinekri. You are absolutely right. I tried that and it indeed fixed the problem.

**Comment by rinekri** [comment]
> Thanks @rinekri. You are absolutely right. I tried that and it indeed fixed the problem.

Nice! I'm happy to help you :)
