### ISSUE TITLE
OTP imple

### ISSUE THREAD

**Issue by sudoharish** [opentrace-community/opentrace-android#49]
OTP implementation in this module through firebase, easiest method.

**Comment by alexissinglaire** [comment]
@sudoharish : what is the issue you encountered?

If you cannot receive OTP SMS, you may refer to similar issue below for resolution. 

Don't forget to check on both android logcat and firebase logs for any error, that might help to drill down into the real issue. 

You might want to check the value in your gradle.properties as most the case the error happened due to entry in that file.

Good luck

https://github.com/opentrace-community/opentrace-android/issues/34
https://github.com/opentrace-community/opentrace-android/issues/19
